version: '3'
services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: db
    environment:
      POSTGRES_DB: eventsearcher
      POSTGRES_USER: eventsearcher
      POSTGRES_PASSWORD: eventsearcher
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  frontend:
    build: ./frontend/eventsearcher
    ports:
      - "8080:80"
    restart: unless-stopped

  backend:
    build: ./backend    
    depends_on:
      - db
    ports:
      - "8081:8081"
    restart: unless-stopped
